# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-12 07:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hway', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Truckdaycount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province', models.CharField(max_length=5)),
                ('date', models.CharField(max_length=20)),
                ('truck11', models.IntegerField()),
                ('truck12', models.IntegerField()),
                ('truck13', models.IntegerField()),
                ('truck14', models.IntegerField()),
                ('truck15', models.IntegerField()),
            ],
        ),
    ]
