# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-12 12:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hway', '0002_truckdaycount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Provinceheavycount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province', models.CharField(max_length=20)),
                ('heavy', models.IntegerField()),
            ],
        ),
    ]
