# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-12 13:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hway', '0004_map'),
    ]

    operations = [
        migrations.AddField(
            model_name='map',
            name='number',
            field=models.CharField(default='0', max_length=5),
        ),
        migrations.AlterField(
            model_name='map',
            name='province',
            field=models.CharField(max_length=20),
        ),
    ]
