# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-13 06:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hway', '0006_auto_20181013_1326'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enweight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=5)),
                ('province', models.CharField(max_length=20)),
                ('stationname', models.CharField(max_length=50)),
                ('weight', models.BigIntegerField()),
            ],
        ),
    ]
