# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-15 09:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hway', '0008_cardaycount'),
    ]

    operations = [
        migrations.AddField(
            model_name='provinceheavycount',
            name='type',
            field=models.CharField(default='en', max_length=10),
        ),
    ]
