# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-15 09:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hway', '0009_provinceheavycount_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provinceheavycount',
            name='type',
            field=models.CharField(max_length=10),
        ),
    ]
