# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-15 10:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hway', '0010_auto_20181015_1753'),
    ]

    operations = [
        migrations.RenameField(
            model_name='provinceheavycount',
            old_name='type',
            new_name='tp',
        ),
    ]
