# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-19 08:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hway', '0013_province'),
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=5)),
                ('province', models.CharField(max_length=50)),
                ('stationname', models.CharField(max_length=50)),
                ('enweight', models.BigIntegerField(default=0)),
                ('exweight', models.BigIntegerField(default=0)),
                ('trafficvolume', models.BigIntegerField(default=0)),
                ('fee', models.BigIntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='province',
            name='exweight',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='province',
            name='trafficvolume',
            field=models.BigIntegerField(default=0),
        ),
    ]
