# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-23 06:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hway', '0017_province_fee'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProvinceNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=5)),
                ('province', models.CharField(max_length=20)),
            ],
        ),
    ]
