# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-24 03:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hway', '0018_provincenumber'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrafficVolume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=5)),
                ('province', models.CharField(max_length=20)),
                ('date', models.DateTimeField()),
                ('total', models.IntegerField(default=0)),
                ('mtc', models.IntegerField(default=0)),
                ('etc', models.IntegerField(default=0)),
                ('tp1', models.IntegerField(default=0)),
                ('tp2', models.IntegerField(default=0)),
                ('tp3', models.IntegerField(default=0)),
                ('tp4', models.IntegerField(default=0)),
                ('tp5', models.IntegerField(default=0)),
                ('tp6', models.IntegerField(default=0)),
                ('tp7', models.IntegerField(default=0)),
                ('tp8', models.IntegerField(default=0)),
                ('tp9', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Weight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=5)),
                ('province', models.CharField(max_length=50)),
                ('date', models.DateTimeField()),
                ('stationname', models.CharField(max_length=50)),
                ('enweight', models.BigIntegerField(default=0)),
                ('exweight', models.BigIntegerField(default=0)),
                ('trafficvolume', models.BigIntegerField(default=0)),
                ('fee', models.BigIntegerField(default=0)),
            ],
        ),
    ]
