# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-24 05:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hway', '0019_trafficvolume_weight'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trafficvolume',
            old_name='tp5',
            new_name='tp11',
        ),
        migrations.RenameField(
            model_name='trafficvolume',
            old_name='tp6',
            new_name='tp12',
        ),
        migrations.RenameField(
            model_name='trafficvolume',
            old_name='tp7',
            new_name='tp13',
        ),
        migrations.RenameField(
            model_name='trafficvolume',
            old_name='tp8',
            new_name='tp14',
        ),
        migrations.RenameField(
            model_name='trafficvolume',
            old_name='tp9',
            new_name='tp15',
        ),
    ]
