# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-24 08:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hway', '0020_auto_20181024_1304'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=5)),
                ('province', models.CharField(max_length=20)),
                ('date', models.DateTimeField()),
                ('total', models.IntegerField(default=0)),
                ('mtc', models.IntegerField(default=0)),
                ('etc', models.IntegerField(default=0)),
                ('tp1', models.IntegerField(default=0)),
                ('tp2', models.IntegerField(default=0)),
                ('tp3', models.IntegerField(default=0)),
                ('tp4', models.IntegerField(default=0)),
                ('tp11', models.IntegerField(default=0)),
                ('tp12', models.IntegerField(default=0)),
                ('tp13', models.IntegerField(default=0)),
                ('tp14', models.IntegerField(default=0)),
                ('tp15', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Pass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=5)),
                ('province', models.CharField(max_length=20)),
                ('enstation', models.CharField(max_length=50)),
                ('exstation', models.CharField(max_length=50)),
                ('trucktrafficvolume', models.BigIntegerField(default=0)),
                ('truckweight', models.BigIntegerField(default=0)),
                ('greentrafficvolume', models.BigIntegerField(default=0)),
                ('greenweight', models.BigIntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='station',
            name='trafficvolume',
        ),
        migrations.AddField(
            model_name='station',
            name='date',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='station',
            name='engreentrafficvolume',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='station',
            name='entrafficvolume',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='station',
            name='exgreentrafficvolume',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='station',
            name='extrafficvolume',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='station',
            name='enweight',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='station',
            name='exweight',
            field=models.IntegerField(default=0),
        ),
    ]
