# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-24 08:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hway', '0022_auto_20181024_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
