# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-25 07:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hway', '0028_area'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fee',
            name='etc',
        ),
        migrations.RemoveField(
            model_name='fee',
            name='mtc',
        ),
    ]
