# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-26 08:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hway', '0033_auto_20181026_1446'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OD',
        ),
    ]
