# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-26 13:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hway', '0035_od'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='od',
            name='enlat',
        ),
        migrations.RemoveField(
            model_name='od',
            name='enlon',
        ),
        migrations.RemoveField(
            model_name='od',
            name='exlat',
        ),
        migrations.RemoveField(
            model_name='od',
            name='exlon',
        ),
    ]
