# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-28 07:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hway', '0036_auto_20181026_2145'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Province',
        ),
    ]
