# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-28 07:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hway', '0037_delete_province'),
    ]

    operations = [
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province', models.CharField(max_length=20)),
                ('enweight', models.BigIntegerField()),
                ('exweight', models.BigIntegerField(default=0)),
                ('entrafficvolume', models.BigIntegerField(default=0)),
                ('extrafficvolume', models.BigIntegerField(default=0)),
                ('fee', models.BigIntegerField(default=0)),
                ('greenentrafficvolume', models.BigIntegerField(default=0)),
                ('greenextrafficvolume', models.BigIntegerField(default=0)),
            ],
        ),
    ]
