# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-30 08:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hway', '0039_province_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='China',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Province', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=20)),
                ('longi', models.FloatField()),
                ('lati', models.FloatField()),
            ],
        ),
        migrations.AlterField(
            model_name='province',
            name='enweight',
            field=models.BigIntegerField(default=0),
        ),
    ]
