# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-30 08:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hway', '0040_auto_20181030_1605'),
    ]

    operations = [
        migrations.RenameField(
            model_name='china',
            old_name='Province',
            new_name='province',
        ),
    ]
