# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-03 07:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hway', '0042_cardtrans'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Carddaycount',
        ),
    ]
