# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-03 07:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hway', '0043_delete_carddaycount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carddaycount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province', models.CharField(max_length=5)),
                ('date', models.DateTimeField()),
                ('card', models.IntegerField()),
                ('mtc', models.IntegerField()),
                ('ratio', models.FloatField()),
            ],
        ),
    ]
