# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-03 07:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hway', '0044_carddaycount'),
    ]

    operations = [
        migrations.AddField(
            model_name='province',
            name='cardtrans',
            field=models.BigIntegerField(default=0),
        ),
    ]
