# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-04 12:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hway', '0045_province_cardtrans'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='diff',
            field=models.BigIntegerField(default=0),
        ),
    ]
