# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-04 13:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hway', '0046_area_diff'),
    ]

    operations = [
        migrations.RenameField(
            model_name='area',
            old_name='diff',
            new_name='trafficdiff',
        ),
    ]
