# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-04 13:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hway', '0048_remove_area_trafficdiff'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=5)),
                ('province', models.CharField(max_length=20)),
                ('date', models.DateTimeField()),
                ('stationname', models.CharField(max_length=50)),
                ('trafficdiff', models.IntegerField(default=0)),
                ('carddiff', models.IntegerField(default=0)),
            ],
        ),
    ]
