# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-05 11:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hway', '0049_diff'),
    ]

    operations = [
        migrations.AddField(
            model_name='diff',
            name='cardnum',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='diff',
            name='encard',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='diff',
            name='excard',
            field=models.IntegerField(default=0),
        ),
    ]
