# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-23 09:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hway', '0052_cycle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cycle',
            name='cycle',
            field=models.CharField(max_length=20),
        ),
    ]
