# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-23 12:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hway', '0053_auto_20181123_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cycle',
            name='cycle',
            field=models.IntegerField(),
        ),
    ]
