# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-24 09:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hway', '0055_chargebytype'),
    ]

    operations = [
        migrations.DeleteModel(
            name='chargebytype',
        ),
    ]
