# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-25 11:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hway', '0058_chargebytype_avg'),
    ]

    operations = [
        migrations.CreateModel(
            name='Potential_c',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('vtype', models.IntegerField()),
                ('p_loss_low', models.FloatField()),
                ('p_loss_high', models.FloatField()),
                ('traffic_loss_low', models.FloatField()),
                ('traffic_loss_high', models.FloatField()),
                ('c', models.FloatField()),
            ],
        ),
    ]
