# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-27 06:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hway', '0060_overload'),
    ]

    operations = [
        migrations.CreateModel(
            name='Axischarge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province', models.CharField(max_length=20)),
                ('traffice_amount', models.IntegerField()),
                ('date', models.DateField()),
                ('axis_low', models.FloatField()),
                ('axis_low_percar', models.FloatField()),
                ('weightfee_amount', models.FloatField()),
                ('weightfee_percar', models.FloatField()),
                ('axis_ref', models.FloatField()),
                ('axis_ref_percar', models.FloatField()),
                ('axis_high', models.FloatField()),
                ('axis_high_percar', models.FloatField()),
            ],
        ),
    ]
