# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-27 07:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hway', '0061_axischarge'),
    ]

    operations = [
        migrations.RenameField(
            model_name='axischarge',
            old_name='traffice_amount',
            new_name='traffic_amount',
        ),
    ]
