# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-29 14:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hway', '0062_auto_20181127_1522'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardIndex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=5)),
                ('province', models.CharField(max_length=20)),
                ('stock', models.IntegerField()),
                ('cycle', models.FloatField()),
                ('turnover', models.FloatField()),
                ('deposition', models.FloatField()),
                ('safestock', models.IntegerField()),
            ],
        ),
    ]
