# Generated by Django 2.1.7 on 2019-03-16 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hway', '0064_idealtrans'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chongqing_od',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_id', models.IntegerField()),
                ('toll', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='LinkToOD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_id', models.CharField(max_length=10)),
                ('number', models.CharField(max_length=5)),
                ('province', models.CharField(max_length=20)),
                ('enstation', models.CharField(max_length=50)),
                ('exstation', models.CharField(max_length=50)),
                ('txl', models.BigIntegerField(default=0)),
            ],
        ),
    ]
