# Generated by Django 2.1.7 on 2019-03-16 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hway', '0065_chongqing_od_linktood'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Chongqing_od',
        ),
    ]
