# Generated by Django 2.1.7 on 2019-03-16 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hway', '0066_delete_chongqing_od'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chongqing_od',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_id', models.IntegerField()),
                ('toll', models.TextField()),
            ],
        ),
    ]
