# Generated by Django 2.1.7 on 2019-03-16 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hway', '0067_chongqing_od'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Chongqing_od',
        ),
    ]
