# Generated by Django 2.1.7 on 2019-03-19 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hway', '0070_remove_zhangxingtong_lng'),
    ]

    operations = [
        migrations.RenameField(
            model_name='zhangxingtong',
            old_name='name',
            new_name='station_name',
        ),
    ]
