# Generated by Django 2.1.7 on 2019-07-02 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hway', '0072_travelcoe'),
    ]

    operations = [
        migrations.CreateModel(
            name='CqODLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_id', models.CharField(max_length=20)),
                ('longi', models.FloatField()),
                ('lati', models.FloatField()),
            ],
        ),
    ]
